publicHoliday = require("./src/holiday.coffee")
console.log publicHoliday.isPublicHoliday(new Date(2015, 0, 1))
console.log publicHoliday.isPublicHoliday(new Date(2015, 0, 12))
console.log publicHoliday.isPublicHoliday(new Date(2015, 1, 11))
console.log publicHoliday.isPublicHoliday(new Date(2015, 2, 21))
console.log publicHoliday.isPublicHoliday(new Date(2015, 3, 29))
console.log publicHoliday.isPublicHoliday(new Date(2015, 4, 4))
console.log publicHoliday.isPublicHoliday(new Date(2015, 4, 5))
console.log publicHoliday.isPublicHoliday(new Date(2015, 4, 6))
console.log publicHoliday.isPublicHoliday(new Date(2015, 6, 20))
console.log publicHoliday.isPublicHoliday(new Date(2015, 8, 21))
console.log publicHoliday.isPublicHoliday(new Date(2015, 8, 23))
console.log publicHoliday.isPublicHoliday(new Date(2015, 9, 12))
console.log publicHoliday.isPublicHoliday(new Date(2015, 10, 3))
console.log publicHoliday.isPublicHoliday(new Date(2015, 10, 23))
console.log publicHoliday.isPublicHoliday(new Date(2015, 11, 23))
module.exports = publicHoliday
